version: "3.9"

services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf
    restart: unless-stopped

    volumes:
      # Single mountpoint for all Telegraf configs
      - ./config:/etc/telegraf:ro

      # Logs to be tailed
      - ./test_data:/flat_files:ro
      - /mnt/current_voyage/satellite_navigation/seapath_1/raw/:/sea_path:ro

    environment:
      - HOSTNAME=${HOSTNAME}
      - INFLUX_URL=http://172.16.29.8:12345/
      - INFLUX_ORG=AADC
      - INFLUX_BUCKET=openrvdas
      - INFLUX_TOKEN=veeoqXe861nJC2g0jO6sRjwBxwbZB9WH6UAvt1nCFmbgSqn9_hIT76gkEmBgxUi1c6vwRBi7Z6sorJ1-UYi47w==

    command:
      - telegraf
      - --config
      - /etc/telegraf/telegraf.conf
      - --config-directory
      - /etc/telegraf/telegraf.d
