[agent]
  interval = "10s"
  flush_interval = "5s"
  metric_batch_size = 5000     # Send larger groups of data at once
  metric_buffer_limit = 100000 # Increase this significantly (e.g., 10x)

[[outputs.influxdb_v2]]
  urls = ["${INFLUX_URL}"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
