[[inputs.file]]
# [[inputs.tail]]
  # watch_method = "inotify"
  files = ["/flat_files/acoustic_net_monitor/acoustic_net_monitor-*.txt"]
  name_override = "acoustic_net_monitor"
  data_format = "grok"
  
grok_patterns = [
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSCMSM2,%{DATA:time_stamp_anm},%{DATA:status_anm},%{DATA:sensor_type_anm},%{DATA:sensor_id_anm},%{DATA:measurement_id_anm},%{DATA:measurement_value_anm},%{DATA:quality_factor_anm},?%{DATA:extra_anm}\*',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSCMMP2,%{DATA:time_stamp_mp_anm},%{DATA:sensor_type_mp_anm},%{DATA:sensor_id_mp_anm},%{DATA:status_mp_anm},%{DATA:tag_mp_anm},%{DATA:extra_mp_anm}\*',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSCMWL[PS],%{DATA:time_stamp_wl_anm},%{DATA:wire_length1_anm},M,%{DATA:wire_length2_anm},M\*',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSCMWT[PS],%{DATA:time_stamp_wt_anm},%{DATA:wire_tension_anm},T\*',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSCMDBS,(?:%{NUMBER:depth_feet_anm:float})?,f,(?:%{NUMBER:depth_meters_anm:float})?,M,(?:%{NUMBER:depth_fathoms_anm:float})?,F\*',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSCMGLL,(?:%{NUMBER:latitude_anm:float})?,%{DATA:n_or_s_anm},(?:%{NUMBER:longitude_anm:float})?,%{DATA:e_or_w_anm},%{DATA:hhmmss_anm},%{DATA:gllqual_anm},%{DATA:mode_anm}\*',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSCMWST,%{DATA:time_stamp_wst_anm},(?:%{NUMBER:surface_water_temperature_anm:float})?,C',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSCMVTG,(?:%{NUMBER:platform_course_true_anm:float})?,T,(?:%{NUMBER:platform_course_magnetic_anm:float})?,M,(?:%{NUMBER:platform_speed_wrt_ground_kts_anm:float})?,N,(?:%{NUMBER:platform_speed_wrt_ground_kmh_anm:float})?,K,%{DATA:mode_anm}\*'
  ]
  
[[processors.starlark]]
  namepass = ["acoustic_net_monitor"]
  source = '''
def apply(metric):
    # Latitude Conversion for $PSCMGLL (DDMM.MMMM to Decimal Degrees)
    lat_raw = metric.fields.get('latitude_anm')
    if lat_raw:
        # DDMM.MMMM format: DD = int(lat/100), MM.MMMM = lat % 100
        deg = int(lat_raw / 100)
        min = lat_raw - (deg * 100)
        lat_deg = deg + (min / 60.0)
        if metric.fields.get('n_or_s_anm') == "S": 
            lat_deg = -lat_deg
        metric.fields['lat_deg_anm'] = lat_deg

    # Longitude Conversion for $PSCMGLL
    lon_raw = metric.fields.get('longitude_anm')
    if lon_raw:
        # DDDMM.MMMM format: DDD = int(lon/100), MM.MMMM = lon % 100
        deg = int(lon_raw / 100)
        min = lon_raw - (deg * 100)
        lon_deg = deg + (min / 60.0)
        if metric.fields.get('e_or_w_anm') == "W": 
            lon_deg = -lon_deg
        metric.fields['lon_deg_anm'] = lon_deg

    return metric
'''