[[inputs.file]]
# [[inputs.tail]]
#   watch_method = "inotify"
#   from_beginning = true
  files = ["/flat_files/svp_derived/svp_derived-*.txt"]
  name_override = "svp_derived"
  data_format = "grok"

  grok_patterns = [ 
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$KSSIS,80,(?:%{NUMBER:speed_of_sound_in_sea_water_calculated:float})?,(?:%{NUMBER:sea_water_temperature_for_calculated_svp:float})?,.*$'
    ]
