# [[inputs.tail]]
[[inputs.file]]
 # watch_method = "inotify"
  #from_beginning = false
  files = ["/flat_files/ipms/ipms-*.txt"]
  name_override = "ipms"
  data_format = "grok"

  grok_patterns = [

    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSDMA,A1,(?:%{NUMBER:md_2_ps_aed_power:float})?,(?:%{NUMBER:md_2_ps_thr_z_power:float})?,(?:%{NUMBER:md_2_sb_aed_power:float})?,(?:%{NUMBER:md_2_sb_thr_z_power:float})?,(?:%{NUMBER:md_1_ps_thr_x_power:float})?,(?:%{NUMBER:md_1_ps_thr_y_power:float})?,(?:%{NUMBER:md_1_sb_thr_x_power:float})?,(?:%{NUMBER:md_1_sb_thr_y_power:float})?,(?:%{NUMBER:cpp_ps_pitch_feedback:float})?,(?:%{NUMBER:cpp_ps_shaft_rpm_feedback:float})?.*(\*.*)?',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSDMA,A2,(?:%{NUMBER:cpp_sb_pitch_feedback:float})?,(?:%{NUMBER:cpp_sb_shaft_rpm_feedback:float})?,(?:%{NUMBER:refrig_1_high_cube_dk_3:float})?,(?:%{NUMBER:refrig_2_high_cube_dk_3:float})?,(?:%{NUMBER:refrig_3_high_cube_dk_3:float})?,(?:%{NUMBER:refrig_4_high_cube_dk_3:float})?,(?:%{NUMBER:refrig_5_high_cube_dk_3:float})?,(?:%{NUMBER:refrig_1_high_cube_dk_5:float})?,(?:%{NUMBER:refrig_2_high_cube_dk_5:float})?,(?:%{NUMBER:refrig_3_high_cube_dk_5:float})?.*(\*.*)?',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSDMA,A3,(?:%{NUMBER:refrig_4_high_cube_dk_5:float})?,(?:%{NUMBER:refrig_5_high_cube_dk_5:float})?,(?:%{NUMBER:refrig_1_dk_4:float})?,(?:%{NUMBER:refrig_2_dk_4:float})?,(?:%{NUMBER:refrig_3_dk_4:float})?,(?:%{NUMBER:refrig_4_dk_4:float})?,(?:%{NUMBER:refrig_5_dk_4:float})?,(?:%{NUMBER:sea_water_flow_wetwell_1:float})?,(?:%{NUMBER:sea_water_flow_wetwell_2:float})?,(?:%{NUMBER:sea_water_flow_wetwell_3:float})?.*(\*.*)?',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PSDMA,A4,(?:%{NUMBER:sea_water_flow_wetwell_4:float})?,(?:%{NUMBER:water_pressure_ucsw_pump_inlet:float})?,(?:%{NUMBER:water_pressure_ucsw_pump_outlet:float})?,(?:%{NUMBER:water_flow_ucsw_supply_line:float})?,(?:%{NUMBER:draught_jet:float})?,(?:%{NUMBER:draught_prop:float})?,(?:%{NUMBER:trace_metal_clean_sea_water_pressure:float})?,(?:%{NUMBER:trace_metal_clean_seawater_flow:float})?,(?:%{NUMBER:aed_ps_torque:float})?,(?:%{NUMBER:aed_sb_torque:float})?.*(\*.*)?',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$PVDRA,A1,(?:%{NUMBER:air_skid_fwd_er:float})?,(?:%{NUMBER:air_skid_aft_er:float})?,(?:%{NUMBER:waterflow_sbe38:float})?,(?:%{NUMBER:aed_ps_load_output_shaft:float})?,(?:%{NUMBER:aed_sb_load_output_shaft:float})?,(?:%{NUMBER:op_cpp_ps_rpm:float})?,(?:%{NUMBER:op_cpp_sb_rpm:float})?.*(\*.*)?',
    '^%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.000000Z"},\$(?:PSDMD|PVDRD),D[0-9]+,.*(\*.*)?'
  ]

  [[processors.converter]]
  namepass = ["ipms"]
  [processors.converter.fields]
    integer = [
      "md_2_ps_aed_power",
      "md_2_ps_thr_z_power",
      "md_2_sb_thr_z_power",
      "md_1_ps_thr_x_power",
      "md_1_ps_thr_y_power",
      "md_1_sb_thr_y_power",
      "sea_water_flow_wetwell_4",
      "water_pressure_ucsw_pump_inlet"
    ]
